/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-ContactsApp-m65eikS-5RAoHjgyz8VMyH-O9omHP3-P",
  "version": "2020-11-20"
}

export default ebconfig;